apiVersion: v2
name: todo-app
description: Evolution Todo Application - Phase 4 Kubernetes Deployment
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes

maintainers:
  - name: Asma Yaseen
    email: asma@example.com
